/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ff9ce1cf-20d6-4a14-b7ff-8e1a0301e3b7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4GBkNReSC",
    "aws_user_pools_web_client_id": "5duhm1mkos4h828t9j0fbd5ptr",
    "oauth": {}
};


export default awsmobile;
